/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.team.app;

import android.app.Activity;
import android.os.Bundle;

import static org.team.app.R.layout.activity_setup_task;

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(activity_setup_task);
    }
}
